###
GET http://localhost:3333/wikipedia/search?query=ellipse&page=1&pageSize=10

###
GET http://localhost:3333/wikipedia/2258

###
GET http://localhost:3333/wikipedia/mostViews/10

###
PATCH http://localhost:3333/wikipedia/increment/13364

###
POST http://localhost:3333/wikipedia/semantic_search
Content-Type: application/json

{
  "query": "Quero documentos que falem sobre machine learning"
}

###
POST http://localhost:3333/signup
Content-Type: application/json

{
  "username": "admaasiz",
  "email": "meu@email.com",
  "password": "0000"
}

###
POST http://localhost:3333/login
Content-Type: application/json

{
  "username": "admin34",
  "password": "0000"
}

###
GET http://localhost:3333/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMzQiLCJpZCI6IjY4NGI2ZWY3NDhmMmE1N2ExMjBmZTAyYiIsImlhdCI6MTc0OTk4OTg3MCwiZXhwIjoxNzQ5OTkwMDUwfQ.ayp1W6YVzZAKoCBc1wq8W3uTh6mXjQWT31WYvL3k6XQ

###
GET http://localhost:3333/user/search/admin2

###

DELETE http://localhost:3333/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMyIsImlkIjoiNjgzODY5NzgxMmEyNzM0Mjg4ZWEyZWQ3IiwiaWF0IjoxNzQ5MTI1MzYxLCJleHAiOjE3NDkxMjU1NDF9.SQjPh0OUsEUeFvjM8Y6zPMFBIL2Ykchko_FOtALkFzk
###
GET http://localhost:3333/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjgzODY4YWJlNDRkM2UzNjk1M2U4NmJkIiwiaWF0IjoxNzQ5MTMwNDgwLCJleHAiOjE3NDkxMzA2NjB9.FSUzKIhW8p-Gn90HDH2_OEHST97ZjRhNypzsTu7TZT0
###

POST http://localhost:3333/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMyIsImlkIjoiNjgzODY5NzgxMmEyNzM0Mjg4ZWEyZWQ3IiwiaWF0IjoxNzQ4NTI3NTM0LCJleHAiOjE3NDg1MjgxMzR9.NZIfjQuYsi_58Ej1Ooscp1tpcazXognHOQUDo1p-Ep4"
}

###
GET http://localhost:3333/users/me/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjgzODY4YWJlNDRkM2UzNjk1M2U4NmJkIiwiaWF0IjoxNzQ5NzY5NTc3LCJleHAiOjE3NDk3Njk3NTd9.tcrqx5kmeolzZjWLDeAl6R_8sesYTn8IdlmqS76Er-w

###
PATCH http://localhost:3333/users/me/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluemFkYSIsImlkIjoiNjg0ZGJkMTdmNjAzNTEwYzA5NjM5MTM4IiwiaWF0IjoxNzQ5OTM2NDk4LCJleHAiOjE3NDk5MzY2Nzh9.unHTb95zDmetogHL4k0EV3sCN5SCifqcwZNuqbZpJWA
Content-Type: application/json

{
  "history": 2,
  "type": "add"
} 

###
GET http://localhost:3333/users/me/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjgzODY4YWJlNDRkM2UzNjk1M2U4NmJkIiwiaWF0IjoxNzQ5NDc1MjMxLCJleHAiOjE3NDk0NzU0MTF9.S3Fqw28mzboU8PvAe9OAJ0U32rlkVKJvtCJXVlcWc8Y

###
PATCH http://localhost:3333/users/me/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluemFkYSIsImlkIjoiNjg0ZGJkMTdmNjAzNTEwYzA5NjM5MTM4IiwiaWF0IjoxNzQ5OTM0NTYzLCJleHAiOjE3NDk5MzQ3NDN9.ITkEt4eAZ5J_WjVBGmLPzQzcVOX6hVixBFwF53Ol_k8
Content-Type: application/json

{
  "favorite": 11,
  "type": "add"
} 

###
GET http://localhost:3333/users/me/shortcuts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjgzODY4YWJlNDRkM2UzNjk1M2U4NmJkIiwiaWF0IjoxNzQ5NDc1MjMxLCJleHAiOjE3NDk0NzU0MTF9.S3Fqw28mzboU8PvAe9OAJ0U32rlkVKJvtCJXVlcWc8Y

###
PATCH http://localhost:3333/users/me/shortcuts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluemFkYSIsImlkIjoiNjg0ZGJkMTdmNjAzNTEwYzA5NjM5MTM4IiwiaWF0IjoxNzQ5OTM2NzQyLCJleHAiOjE3NDk5MzY5MjJ9.wTYoQjnmGKNq7Wn2okDstP2Sx7vmhbNT4djZr2R1npE
Content-Type: application/json

{
  "quickAccess": 2,
  "type": "remove"
}

###
GET http://localhost:3333/users/me/folders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMzQiLCJpZCI6IjY4NGI2ZWY3NDhmMmE1N2ExMjBmZTAyYiIsImlhdCI6MTc0OTk5MDE5MiwiZXhwIjoxNzQ5OTkwMzcyfQ.DuhY08ECGmmABt67Uzcypa39boUoRoZ0B1iv-9kF5Nk

###
GET http://localhost:3333/users/me/folders/lidos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMzQiLCJpZCI6IjY4NGI2ZWY3NDhmMmE1N2ExMjBmZTAyYiIsImlhdCI6MTc0OTk5MTA3MiwiZXhwIjoxNzQ5OTkxMjUyfQ.fYpmYbM-FSQzflOhNPSu05th7reUX-BZl5NNmpCteq0

###
PATCH http://localhost:3333/users/me/folders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMzQiLCJpZCI6IjY4NGI2ZWY3NDhmMmE1N2ExMjBmZTAyYiIsImlhdCI6MTc0OTk5MTM3MywiZXhwIjoxNzQ5OTkxNTUzfQ.yLBCMiDn8krkC1auaSddhUb6y-cBCB-SxKq3XsWHDcc
Content-Type: application/json

{
  "type": "remove",
  "folders": {
    "folderName": "teste2",
  "wikipages": [1, 2, 3, 5]
  }
}

###
PATCH http://localhost:3333/users/me/folders/teste/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMzQiLCJpZCI6IjY4NGI2ZWY3NDhmMmE1N2ExMjBmZTAyYiIsImlhdCI6MTc1MDAxMTU4MCwiZXhwIjoxNzUwMDExNzYwfQ.l3B_Om2y2HzBfRcTibkJkNGe-Oh94iMuFKJF0sfYGLA
Content-Type: application/json

{
  "type": "remove",
  "item": 2
}


###

GET http://localhost:3333/users/me/general-settings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjgzODY4YWJlNDRkM2UzNjk1M2U4NmJkIiwiaWF0IjoxNzQ5NDc4MTQ3LCJleHAiOjE3NDk0NzgzMjd9.reqi-kPIanNruZaiSCYFo3Zt497sqHgFtR_X7gzPMS0

###
PATCH http://localhost:3333/users/me/general-settings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluemFkYSIsImlkIjoiNjg0YjZlZjc0OGYyYTU3YTEyMGZlMDJiIiwiaWF0IjoxNzQ5OTI2MzI0LCJleHAiOjE3NDk5MjY1MDR9.oubT6C6fSXjt1Y-5BSnF2Rk1-V6XJelWsOIXSHFoS-o
Content-Type: application/json

{
  "backgroundImage": "http://image",
  "themeColor": "blue",
  "outputMethod": "diffScreen"
}

###
GET http://localhost:3333/users/me/card-settings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjgzODY4YWJlNDRkM2UzNjk1M2U4NmJkIiwiaWF0IjoxNzQ5NTk4ODg5LCJleHAiOjE3NDk1OTkwNjl9.I11gS2RQ2NyOrp7b0MsdhCHTFQaS4zeCzepF_LHYsWs

###
PATCH http://localhost:3333/users/me/card-settings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluemFkYSIsImlkIjoiNjg0YjZlZjc0OGYyYTU3YTEyMGZlMDJiIiwiaWF0IjoxNzQ5OTEyODUwLCJleHAiOjE3NDk5MTMwMzB9.LtcrVCSc-507KOyOMvprrxxkmwUEYqqlYtrXEOJouwM
Content-Type: application/json

{
  "fontFamily": "Inter"
}

###
PATCH http://localhost:3333/users/me/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluemFkYSIsImlkIjoiNjg0YjZlZjc0OGYyYTU3YTEyMGZlMDJiIiwiaWF0IjoxNzQ5OTI2NzYxLCJleHAiOjE3NDk5MjY5NDF9.I3-GnSWnvnS0KIK-2iRe99IOeOVdzWZGU7n5Pwo98MQ
Content-Type: application/json

{
  "username": "admin2",
  "status": "focado",
  "avatar": "http://image"
}
