###
GET http://localhost:3333/wikipedia/search?query=quadratic+equation&page=1&pageSize=10

###
GET http://localhost:3333/wikipedia/332

###
GET http://localhost:3333/wikipedia/mostViews/9

###
GET http://localhost:3333/wikipedia/increment/332

###
POST http://localhost:3333/signup
Content-Type: application/json

{
  "username": "admin53",
  "email": "meu@email53.com",
  "password": "0000"
}

###
POST http://localhost:3333/login
Content-Type: application/json

{
  "username": "admin2",
  "password": "0000"
}

###
GET http://localhost:3333/user/6837225fc464463f10ccfdf1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDg0NTMxODIsImV4cCI6MTc0ODQ1MzM2Mn0.3EkbKRnWibw3vRSweO2qqbC2kZjGxXRMfdD_uU8e1qg

###
GET http://localhost:3333/user/search/admin3

###

DELETE http://localhost:3333/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMyIsImlkIjoiNjgzODY5NzgxMmEyNzM0Mjg4ZWEyZWQ3IiwiaWF0IjoxNzQ5MTI1MzYxLCJleHAiOjE3NDkxMjU1NDF9.SQjPh0OUsEUeFvjM8Y6zPMFBIL2Ykchko_FOtALkFzk
###
GET http://localhost:3333/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjgzODY4YWJlNDRkM2UzNjk1M2U4NmJkIiwiaWF0IjoxNzQ5MTMwNDgwLCJleHAiOjE3NDkxMzA2NjB9.FSUzKIhW8p-Gn90HDH2_OEHST97ZjRhNypzsTu7TZT0
###

POST http://localhost:3333/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMyIsImlkIjoiNjgzODY5NzgxMmEyNzM0Mjg4ZWEyZWQ3IiwiaWF0IjoxNzQ4NTI3NTM0LCJleHAiOjE3NDg1MjgxMzR9.NZIfjQuYsi_58Ej1Ooscp1tpcazXognHOQUDo1p-Ep4"
}